dataset:
    name: &dataset_name 'coco2017'
    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    num_workers: 4
    aspect_ratio_group_factor: 3
    splits:
        train:
            images: !join [*root_dir, '/train2017']
            annotations: !join [*root_dir, '/annotations/person_keypoints_train2017.json']
            remove_non_annotated_imgs: False
        val:
            images: !join [*root_dir, '/val2017']
            annotations: !join [*root_dir, '/annotations/person_keypoints_val2017.json']
            remove_non_annotated_imgs: False
        test:
            images: !join [*root_dir, '/val2017']
            annotations: !join [*root_dir, '/annotations/person_keypoints_val2017.json']
            remove_non_annotated_imgs: False

model:
    name: &model_name 'keypoint_rcnn'
    backbone:
        name: &backbone_name 'resnet50'
        params:
            pretrained: True
            freeze_layers: True
        ext_config:
            backbone_frozen: True
            threshold: 0.5
            ckpt: !join ['./resource/ckpt/ext/', *dataset_name, '-', *model_name, '-backbone_ext_', *backbone_name ,'.pt']
    params:
        num_classes: 2
        num_keypoints: 17
        pretrained: True
    experiment: &experiment !join [*dataset_name, '-', *model_name, '-backbone_', *backbone_name]
    ckpt: !join ['./resource/ckpt/org/', *experiment, '.pt']

train:
    num_epochs: 30
    batch_size: 2
    log_freq: 10000
    optimizer:
        type: 'SGD'
        params:
            lr: 0.001
            momentum: 0.9
            weight_decay: 0.0001
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [15, 25]
            gamma: 0.1

test:
    batch_size: 1