dataset:
    name: &dataset_name 'coco2017'
    task_name: 'coco_bbox'
    root: !join ['./resource/dataset/', *dataset_name, '/']
    num_workers: 4
    aspect_ratio_group_factor: 0
    splits:
        train: 'train'
        val: 'val'
        test: 'val'

input_shape: [3, 300, 400]

model:
    name: &model_name 'faster_rcnn'
    params:
        backbone_name: &backbone_name 'resnet50'
        backbone_pretrained: True
        num_classes: 91
        pretrained: True
    experiment: &experiment !join [*dataset_name, '-', *model_name, '-backbone_', *backbone_name]
    ckpt: !join ['./resource/ckpt/org/', *experiment, '.pt']

train:
    num_epochs: 13
    batch_size: 2
    log_freq: 1000
    optimizer:
        type: 'SGD'
        params:
            lr: 0.0075  # 0.02 / 8 * num_gpus
            momentum: 0.9
            weight_decay: 0.0001
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [8, 11]
            gamma: 0.1

test:
    batch_size: 1
