dataset:
    name: &dataset_name 'coco2017'
    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    num_workers: 4
    aspect_ratio_group_factor: 3
    splits:
        train:
            images: !join [*root_dir, '/train2017']
            annotations: !join [*root_dir, '/annotations/instances_train2017.json']
            remove_non_annotated_imgs: True
            jpeg_quality:
        val:
            images: !join [*root_dir, '/val2017']
            annotations: !join [*root_dir, '/annotations/instances_val2017.json']
            remove_non_annotated_imgs: False
            jpeg_quality:
        test:
            images: !join [*root_dir, '/val2017']
            annotations: !join [*root_dir, '/annotations/instances_val2017.json']
            remove_non_annotated_imgs: False
            jpeg_quality:

model:
    name: &model_name 'mask_rcnn'
    backbone:
        name: &backbone_name 'resnet50'
        params:
            pretrained: True
            freeze_layers: True
    params:
        num_classes: 91
        pretrained: True
    experiment: &experiment !join [*dataset_name, '-', *model_name, '-backbone_', *backbone_name]
    ckpt: !join ['./resource/ckpt/org/', *experiment, '.pt']

train:
    num_epochs: 26
    batch_size: 2
    log_freq: 1000
    optimizer:
        type: 'SGD'
        params:
            lr: 0.0075  # 0.02 / 8 * num_gpus
            momentum: 0.9
            weight_decay: 0.0001
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [16, 22]
            gamma: 0.1

test:
    batch_size: 1
