dataset:
    name: &dataset_name 'coco2017'
    root: &data_dir !join ['./resource/data/', *dataset_name, '/']
    data:
        annot_prefix: &annot_prefix !join [*data_dir, 'annotations/instances_']
        img_prefix: &img_prefix !join [*data_dir, 'images/']
        train:
            annotation: !join [*annot_prefix, 'train2017.json']
            img_dir: !join [*img_prefix, 'train2017/']
        val:
            annotation: !join [*annot_prefix, 'val2017.json']
            img_dir: !join [*img_prefix, 'val2017/']

input_shape: [3, 640, 640]

teacher_model:
    config: './config/org/pretrained_retinanet50.yaml'
    extract_designed_module: False
    start_idx: 0
    end_idx: 11 # 11, 17, 20 for vers. 1, 2, 3

student_model:
    type: &smodel_type 'retinanet50_head_mimic'
    version: &ver '1'
    experiment: &distill_experiment !join [*dataset_name, '-', *smodel_type, '-ver', *ver]
    ckpt: !join ['./resource/ckpt/mimic/', *distill_experiment, '.pt']

mimic_model:
    type: &mmodel_type 'retinanet50_mimic'
    experiment: &mimic_experiment !join [*dataset_name, '-', *mmodel_type, '-ver', *ver]
    ckpt: !join ['./resource/model/mimic/', *mimic_experiment, '.pkl']

train:
    epoch: 30
    batch_size: 2
    interval: 50
    optimizer:
        type: 'Adam'
        params:
            lr: 0.001
    criterion:
        type: 'MSELoss'
        params:
            reduction: 'sum'
    log: !join ['./log/mimic/', *mimic_experiment, '-train.txt']

test:
    batch_size: 1
    result:
        org: !join ['./result/', *mimic_experiment, '-org-test.json']
        mimic: !join ['./result/', *mimic_experiment, '-mimic-test.json']
    log: !join ['./log/mimic/', *mimic_experiment, '-test.txt']
